# Cloud server configurations
cloud:
  display_server:
    host: '0.0.0.0'
    port: 6001
    url: 'http://0.0.0.0:6001'

# Edge node configurations
edge:
  processing_server:
    host: '0.0.0.0'
    port: 6002
    url: 'http://0.0.0.0:6002'
  
  models:
    default: 's'
    weights_dir: 'edge/models'
    allowed_sizes: ['n', 's', 'm', 'l', 'x']

# Video stream configurations
stream:
  source_path: 'data'
  frame_delay: 0.5
  default_id: 'test_stream_1'