# Cloud server configurations
cloud:
  display_server:
    host: '0.0.0.0'
    port: 6011
    url: 'http://0.0.0.0:6011'

# Edge node configurations
edge:
  processing_server:
    host: '0.0.0.0'
    port: 6012
    url: 'http://0.0.0.0:6012'
  
  models:
    default: 's'
    weights_dir: 'edge/models'
    allowed_sizes: ['n', 's', 'm', 'l', 'x']

# Video stream configurations
stream:
  source_path: 'data'
  frame_delay: 0.5
  default_id: 'test_stream_1'

# Dynamic stream configurations
dynamic_stream:
  source_path: 'data'
  default_id: 'dynamic_stream_1'
  fps_control:
    min_fps: 1
    max_fps: 10
    min_duration: 60
    max_duration: 300