# Cloud server configurations
cloud:
  display_server:
    host: '0.0.0.0'
    port: 6021
    url: 'http://127.0.0.1:6021'

# Edge node configurations
edge:
  processing_server:
    host: '0.0.0.0'
    port: 6022
    url: 'http://127.0.0.1:6022'
  
  models:
    default: 's'
    weights_dir: 'edge/models'
    allowed_sizes: ['n', 's', 'm', 'l', 'x']

# Video stream configurations
stream:
  source_path: 'data'
  frame_delay: 0.5
  default_id: 'test_stream_1'

# Dynamic stream configurations
dynamic_stream:
  source_path: 'data'
  default_id: 'dynamic_stream_1'
  fps_control:
    min_fps: 5
    max_fps: 20
    min_duration: 120
    max_duration: 600

# queue length
queue:
  max_length: 50
  threshold_length: 10